config/routes.rb
Rails.application.routes.draw do
 root 'pages#index'
 get '/team', to: 'team#show'
 get '/contact', to: 'contact#show'
 get '/welcome/:first_name', to: 'welcome#show'
 get '/author/:author_id', to: 'author#show', as: 'author'
resources :users
resources :gossips
resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
  	has_many :gossip_tags
  	has_many :tags, through: :gossip_tags

end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossip_tags
  	has_many :gossips, through: :gossip_tags

  	validates :title,
  	presance: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city
	has_many :gossips

  	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    
   
    validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }   	



end # class

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	def show
		@user = User.find(params[:author_id])
		
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def show
		
	end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def index # methode qui recupere tous le potins les envoie a la VIEW
  		@gossips = Gossip.all
  		@users = User.all
  	end

  # recupere le potin concerne et l'envoie a la veiw show(show.html.erb)
 	 def show
     @gossip = Gossip.find(params[:id])
    @users = User.all
  	
  	end

  # cree un potin vide et l'envoie a une VIEWqui affiche le formulaire pour  (le remplir new.html.erb)
  	def new
  	
  	end

 # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur   # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
 # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé
 	def create
 	 @gossip = Gossip.new(title: params[:title], content: params[:content]) # 
    	if @gossip.save
        flash[:success] = "ok"
      		redirect_to root_path 

    	else
        flash[:danger] = "nop"
      	render new_gossip_path # l'utils reste sur la page 
    	end

 	end

 # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
 	def edit
    @gossip = Gossip.find(params[:id])
  		
 	end

 # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
 # pour info, le contenu de ce formulaire sera accessible dans le hash params
 # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
	def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(title: params[:title], content: params[:content])
      flash[:success] = "ok"
      redirect_to gossip_path
    else
      flash[:danger] = "nop"
      render edit_gossip_path
    end
  end
    	
 
 # Méthode qui récupère le potin concerné et le détruit en base
 # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
	def destroy
       @gossip = Gossip.find(params[:id])
    if @gossip.destroy
      flash[:success] = "ok"
      redirect_to gossips_path
    else
      flash[:danger] = "nop"
      render gossip_path
    end
	
	end

end # class

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@gossips = Gossip.all
    @users = User.all
  	
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
	def show
		
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def show
		@user = User.find(params[:id])
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 # before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @gossips = Gossip.all
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  def create
     @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation],
      city: City.last
    )
    if @user.save
      redirect_to users_path 
    else 
      logger.debug "User created:@user.inspect"
      puts "#{@user}"
      puts "#{@user.errors.inspect}"
      flash[:danger] = "Nop"   
      render new_user_path
    end
  end

  def update
   
  end


 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def show
		@first_name = params[:first_name]
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    	User.find_by(id: session[:user_id])
  	end

   def log_in(user)
    session[:user_id] = user.id
  end
 
  def logged_in?
    session[:user_id] != nil ? true : false
  end
# TODO : verifie si il est author
  def creator?(object)
    current_user == object.user ? true : false
   
  end

  private

  def authenticate_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def has_access
    # on vérifie si c'est bien le créateur du gossip en question sinon on le redirige
    unless creator?(Gossip.find(params[:id]))
      flash[:danger] = "Vous n'avez pas accès à cette page."
      redirect_to root_path
    end
  end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/user/show.html.erb
 <div class="card-body">
    <h5 class="card-title">Auteur</h5>
    <p class="card-text"><%= @user.first_name %> <%= @user.last_name %></p>
</div>
  <div class="card-body">
    <h5 class="card-title">Description</h5>
    <p class="card-text"><%= @user.description %></p>
</div>
  <div class="card-body">
    <h5 class="card-title">Email</h5>
    <p class="card-text"><%= @user.email %></p>
  </div>
  <div class="card-body">
    <h5 class="card-title">Age</h5>
    <p class="card-text"><%= @user.age %></p>
  </div>
  <div class="card-body">
    <h5 class="card-title">Ville</h5>
    <p class="card-text"><%= @user.city.name %> (<%= @user.city.zip_code %>) <%= link_to 'Voir', city_path(@user.city.id), class: 'btn btn-primary btn-sm' %></p>
  </div>
</div>

<h2 class="text-center">Tous les gossips de <%= @user.first_name %> :</h2>

<% @user.gossips.each do |gossip| %>
  <!-- on fait une boucle pour afficher chaque gossip -->
  <div class="card my-4 mx-auto" style="max-width: 50rem;">
    <div class="card-body">
      <h5 class="card-title"><%= gossip.id %>. <%= gossip.title %></h5>
      <p class="card-text"><%= gossip.content %></p>
      <p class="card-text"><%= @user.first_name %></p>
      <span class="btn btn-primary"><%= link_to 'Plus sur gossip', gossip_path(gossip.id) %></span>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="card text-center">
  <div class="card-header">
    <h3>Bienvenue<% if current_user %> <%= current_user.first_name.capitalize %> <% end%></h3>
  </div>
  <div class="card-body">
    <p class="card-text">Comme ca va ? </p>
  </div>
</div>



<div class="d-flex flex-wrap justify-content-around mx-4">
  <% @gossips.each do |gossip| %>
    <div class="card m-4" style="width: 18rem;">
      <div class="card-body"><center>
        <h5 class="card-title"><%= gossip.id %>. <%= gossip.title %></h5>
        <p class="card-text"><%= @users.find(gossip.user_id).first_name %></p>
        <a href= "<%= author_path(gossip.user_id) %>">plus sur author ..</a><br />
        <%= link_to 'Edit', edit_gossip_path(gossip) %> <%= link_to 'Show', gossip %>
        <%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Vraiment ??' } %>
      </div>
  </center>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="card text-center mx-auto my-2" style="max-width: 50rem;">

  <div class="card-body">
    <%= form_tag users_path, method: "post", class: "form-group" do %>
     <% form_authenticity_token %>

      <div class="form-group form-check">	
      	<h4>Creer ton compte</h4>
        <%= label_tag 'Prénom' %>
        <%= text_field_tag 'first_name', nil, class: "form-control" %>
      </div>

      <div class="form-group form-check">
        <%= label_tag 'Nom' %>
        <%= text_field_tag 'last_name', nil, class: "form-control" %>
      </div>

      <div class="form-group form-check">
        <%= label_tag 'Email' %>
        <%= text_field_tag 'email', nil, class: "form-control" %>
      </div>

      <div class="form-group form-check">
        <%= label_tag 'Mot de passe' %>
        <%= text_field_tag 'password', nil, class: "form-control" %>
      </div>

      <div class="form-group form-check">
        <%= label_tag 'Confirmation du mot de passe' %>
        <%= text_field_tag 'password_confirmation', nil, class: "form-control" %> 
	

      </div> 
      <% link_to users_path %> 
   <%= submit_tag "Créer", class: "btn btn-primary" %><br>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>