config/routes.rb
Rails.application.routes.draw do
 root 'pages#index'
 get '/team', to: 'team#show'
 get '/contact', to: 'contact#show'
 get '/welcome/:first_name', to: 'welcome#show'
 get '/author/:author_id', to: 'author#show', as: 'author'
resources :users
resources :gossips
resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
  	has_many :gossip_tags
  	has_many :tags, through: :gossip_tags

end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossip_tags
  	has_many :gossips, through: :gossip_tags

  	validates :title,
  	presance: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city
	has_many :gossips

  	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
    
   
    validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }   	



end # class

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@gossips = Gossip.all
    @users = User.all
  	
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
	def show
		
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def show
		@user = User.find(params[:id])
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    	User.find_by(id: session[:user_id])
  	end

   def log_in(user)
    session[:user_id] = user.id
  end
 
  def logged_in?
    session[:user_id] != nil ? true : false
  end
# TODO : verifie si il est author
  def creator?(object)
    current_user == object.user ? true : false
   
  end

  private

  def authenticate_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def has_access
    # on vérifie si c'est bien le créateur du gossip en question sinon on le redirige
    unless creator?(Gossip.find(params[:id]))
      flash[:danger] = "Vous n'avez pas accès à cette page."
      redirect_to root_path
    end
  end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Home</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
         <a class="nav-link"<%= link_to "Equipe", team_path %> </a>
      </li>
      <li class="nav-item">
         <a class ="nav-link"<%= link_to "Contact",contact_path %></a>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Se connecter
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to 'Créer un compte', new_user_path, class: "dropdown-item" %>
        <%= link_to 'Se connecter', new_session_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</nav>
      
  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<!-- home -->
<div class="d-flex flex-wrap justify-content-around mx-4">
  <% @gossips.each do |gossip| %>
    <div class="card m-4" style="width: 18rem;">
      <div class="card-body"><center>
        <h5 class="card-title"><%= gossip.id %>. <%= gossip.title %></h5>
        <p class="card-text"><%= @users.find(gossip.user_id).first_name %></p>
       	<a href= "<%= author_path(gossip.user_id) %>">plus sur author ..</a><br />

      </div>
  </center>
    </div>
  <% end %>
</div>